Fix linker errors with VTK-6.0 and MPICH in Travis CI
On Ubuntu Trusty (14.04), the linker fails to link unit tests and
applications against library hbrs-mpl and throws an error at one of the
library-exported MPI functions, e.g.:
  /usr/bin/ld: CMakeFiles/fn_pca_filter.dir/test.cpp.o: undefined reference to symbol 'ompi_mpi_comm_null'
  //usr/lib/libmpi.so.1: error adding symbols: DSO missing from command line

VTK 6.0 at Ubuntu Trusty (14.04) is linked against OpenMPI. The CMake
files installed in line with VTK (/usr/lib/cmake/vtk-6.0/Modules/vtkParallelMPI.cmake)
add the OpenMPI header paths to the library's CMake include directories:
  set(vtkParallelMPI_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-6.0;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi")

So the library uses OpenMPI headers instead of MPICH headers. We did not
add VTK header paths and did not link libraries to our application
within CMake and thus the linker is not able to resolve those referenced
OpenMPI symbols. To workaround this, we patch the VTK CMake files and
remove those OpenMPI includes.